// FILE: client/src/admin/UserManagement.jsx

import React, { useState, useEffect, useMemo, useCallback } from 'react';
import { FaRegEdit, FaTrash, FaEye, FaEyeSlash, FaPlus, FaUserShield } from 'react-icons/fa';
import { useNavigate, Link } from 'react-router-dom';
import { useUserManagement } from './hooks/useUserManagement';
import { useRoleManagement } from './hooks/useRoleManagement';
import { useSorting } from './hooks/useSorting';
import { useSearchFilter } from './hooks/useSearchFilter';
import { usePagination } from './hooks/usePagination';
import DeleteConfirmModal from './components/DeleteConfirmModal';
import { formatDateToLocal } from '../utils/dateUtils'; 
import { useAuth } from './AuthContext'; 
import { MdSkipPrevious, MdSkipNext, MdFirstPage, MdLastPage } from 'react-icons/md';
import CryptoJS from 'crypto-js';


const UserManagement = () => {
    const navigate = useNavigate();
    const { users, loading: usersLoading, error: usersErrorHook, addUser, deleteUser } = useUserManagement();
    const { roles, loading: rolesLoading, error: rolesErrorHook } = useRoleManagement();
    const { hasPermission, loadingPermissions } = useAuth(); 

    const [newUserData, setNewUserData] = useState({
        email: '',
        displayName: '',
        password: '',
        confirmPassword: '',
        roleId: '', // Role ID is crucial for UID generation
        phone: '',
        companyName: '',
        isActive: true,
    });

    const [showPassword, setShowPassword] = useState(false);
    const [showConfirmPassword, setShowConfirmPassword] = useState(false);
    const [formError, setFormError] = useState('');
    const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
    const [userToDelete, setUserToDelete] = useState(null);

    const [filterText, setFilterText] = useState('');
    const [filterType, setFilterType] = useState('');

    const { sortedData, requestSort, getSortIndicator } = useSorting(users);
    const filteredBySearch = useSearchFilter(sortedData, filterText, filterType);
    const { paginatedData, currentPage, totalPages, setCurrentPage } = usePagination(filteredBySearch, 10); // Display 10 users per page


    const handleInputChange = (e) => {
        const { name, value, type, checked } = e.target;
        setNewUserData(prev => ({
            ...prev,
            [name]: type === 'checkbox' ? checked : value
        }));
    };

   const handleAddNewUser = async (e) => {
        e.preventDefault();
        if (!hasPermission('add_user')) {
            setFormError("You don't have permission to add users.");
            return;
        }
        if (!newUserData.email.trim() || !newUserData.displayName.trim()) {
            setFormError('Email and Display Name are required.');
            return;
        }
        if (!newUserData.password.trim()) {
            setFormError('Password is required for new users.');
            return;
        }
        if (newUserData.password !== newUserData.confirmPassword) {
            setFormError('Passwords do not match.');
            return;
        }
        if (!newUserData.roleId) {
            setFormError('Role is required to generate User ID.');
            return;
        }
        setFormError('');

        const staticKey = 'meriChabi'; 
        const encryptedPassword = CryptoJS.AES.encrypt(newUserData.password, staticKey).toString();

        const success = await addUser({
            // UID will be generated by the hook based on role, serial, and date
            email: newUserData.email,
            displayName: newUserData.displayName,
            roleId: newUserData.roleId, // Pass roleId for UID generation
            phone: newUserData.phone,
            companyName: newUserData.companyName,
            isActive: newUserData.isActive,
            password: encryptedPassword
        });

        if (success) {
            setNewUserData({ email: '', displayName: '', password: '', confirmPassword: '', roleId: '', phone: '', companyName: '', isActive: true });
            setShowPassword(false);
            setShowConfirmPassword(false);
        } else if(usersErrorHook) {
             setFormError(usersErrorHook);
        }
    };
    
    const handleDeleteClick = (user) => {
        if (!hasPermission('delete_user')) {
            alert("You don't have permission to delete users.");
            return;
        }
        setUserToDelete(user); // user.id here is the document ID (new UID or email)
        setShowDeleteConfirm(true);
    };

    const confirmDeleteUser = async () => {
        if (userToDelete && hasPermission('delete_user')) {
            await deleteUser(userToDelete.id); // Pass document ID for deletion
            setShowDeleteConfirm(false);
            setUserToDelete(null);
        }
    };
    
    const getRoleName = useCallback((roleId) => {
        const role = roles.find(r => r.id === roleId);
        return role ? role.name : 'No Role';
    }, [roles]);

    const columns = useMemo(() => [
        { 
            key: 'uid', 
            label: 'User ID', 
            sortable: true,
            render: (uidVal, item) => uidVal || item.id 
        },
        { 
            key: 'displayName', 
            label: 'Name', 
            sortable: true,
        },
        { key: 'email', label: 'Email', sortable: true },
        { 
            key: 'roleId', 
            label: 'Role', 
            sortable: true,
            render: (roleId) => (
                <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${roleId ? 'bg-blue-700 text-blue-100' : 'bg-gray-600 text-gray-300'}`}>
                    <FaUserShield className="mr-1.5" />
                    {getRoleName(roleId)}
                </span>
            )
        },
        { key: 'companyName', label: 'Company', sortable: true, render: val => val || 'N/A' },
        { 
            key: 'createdAt', 
            label: 'Created At', 
            sortable: true, 
            render: val => val ? `${formatDateToLocal(val)}` : 'N/A'
        },
        { 
            key: 'isActive', 
            label: 'Status', 
            sortable: true,
            render: (isActive) => (
                <span className={`px-2 py-1 inline-flex text-xs leading-5 font-semibold rounded-full ${isActive ? 'bg-green-700 text-green-100' : 'bg-red-700 text-red-100'}`}>
                    {isActive ? 'Active' : 'Inactive'}
                </span>
            )
        },
        {
            key: 'actions',
            label: 'Actions',
            sortable: false,
            render: (_, item) => ( // item.id is the document ID
                <div className="flex items-center space-x-2">
                    {hasPermission('view_user_details') && (
                        <Link to={`/admin/users/${item.id}`} state={{ editMode: false }} className="text-yellow-400 hover:text-yellow-300 p-1.5 rounded-md transition-colors" title="View User">
                            <FaEye size={16} />
                        </Link>
                    )}
                    {(hasPermission('edit_user_details') || hasPermission('edit_user_role') || hasPermission('edit_user_status') || hasPermission('reset_user_password') ) && (
                        <Link to={`/admin/users/${item.id}`} state={{ editMode: true }} className="text-blue-400 hover:text-blue-300 p-1.5 rounded-md transition-colors" title="Edit User">
                            <FaRegEdit size={16} />
                        </Link>
                    )}
                    {hasPermission('delete_user') && (
                        <button onClick={() => handleDeleteClick(item)} className="text-red-500 hover:text-red-400 p-1.5 rounded-md transition-colors" title="Delete User">
                            <FaTrash size={16} />
                        </button>
                    )}
                </div>
            )
        }
    // eslint-disable-next-line react-hooks/exhaustive-deps
    ], [getRoleName, navigate, formatDateToLocal, hasPermission]); 


    const loading = usersLoading || rolesLoading || loadingPermissions; 
    const error = usersErrorHook || rolesErrorHook;

    if (loading && !users.length && !error) return <div className="p-6 text-center text-gray-300">Loading user data...</div>;
    if (error && !formError && !usersErrorHook) return <div className="p-6 text-center text-red-400">Error: {error}</div>;


    return (
        <div className="p-4 md:p-6 bg-gray-900 text-gray-100 min-h-screen">
            <h1 className="text-2xl md:text-3xl font-bold mb-6 text-yellow-500">User Management</h1>

            {formError && <p className="text-red-400 mb-4 p-3 bg-red-900/30 rounded-md">{formError}</p>}
            {usersErrorHook && !formError && <p className="text-red-400 mb-4 p-3 bg-red-900/30 rounded-md">{usersErrorHook}</p>}


            {hasPermission('add_user') && (
                <form onSubmit={handleAddNewUser} className="mb-8 p-6 bg-gray-800 rounded-lg shadow-xl border border-gray-700">
                    <h2 className="text-xl font-semibold mb-4 text-yellow-400">Add New User</h2>
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mb-4">
                        <input
                            type="email" name="email" placeholder="Email" value={newUserData.email}
                            onChange={handleInputChange} required
                            className="p-3 bg-gray-700 text-white border border-gray-600 rounded-md focus:ring-2 focus:ring-yellow-500 focus:border-yellow-500"
                        />
                        <input
                            type="text" name="displayName" placeholder="Display Name" value={newUserData.displayName}
                            onChange={handleInputChange} required
                            className="p-3 bg-gray-700 text-white border border-gray-600 rounded-md focus:ring-2 focus:ring-yellow-500 focus:border-yellow-500"
                        />
                         <input
                            type="tel" name="phone" placeholder="Phone Number" value={newUserData.phone}
                            onChange={handleInputChange}
                            className="p-3 bg-gray-700 text-white border border-gray-600 rounded-md focus:ring-2 focus:ring-yellow-500 focus:border-yellow-500"
                        />
                        <div className="relative">
                            <input
                                type={showPassword ? "text" : "password"} name="password" placeholder="Password" value={newUserData.password}
                                onChange={handleInputChange} required
                                className="w-full p-3 bg-gray-700 text-white border border-gray-600 rounded-md focus:ring-2 focus:ring-yellow-500 focus:border-yellow-500"
                            />
                            <button 
                                type="button" 
                                onClick={() => setShowPassword(!showPassword)} 
                                className="absolute inset-y-0 right-0 px-3 flex items-center text-gray-400 hover:text-gray-200"
                                aria-label={showPassword ? "Hide password" : "Show password"}
                            >
                                {showPassword ? <FaEyeSlash /> : <FaEye />}
                            </button>
                        </div>
                        <div className="relative">
                            <input
                                type={showConfirmPassword ? "text" : "password"}
                                name="confirmPassword"
                                placeholder="Confirm Password"
                                value={newUserData.confirmPassword}
                                onChange={handleInputChange}
                                required
                                className="w-full p-3 bg-gray-700 text-white border border-gray-600 rounded-md focus:ring-2 focus:ring-yellow-500 focus:border-yellow-500"
                            />
                            <button
                                type="button"
                                onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                                className="absolute inset-y-0 right-0 px-3 flex items-center text-gray-400 hover:text-gray-200"
                                aria-label={showConfirmPassword ? "Hide confirm password" : "Show confirm password"}
                            >
                                {showConfirmPassword ? <FaEyeSlash /> : <FaEye />}
                            </button>
                        </div>
                         <select
                            name="roleId" value={newUserData.roleId} onChange={handleInputChange} required
                            className="p-3 bg-gray-700 text-white border border-gray-600 rounded-md focus:ring-2 focus:ring-yellow-500 focus:border-yellow-500"
                        >
                            <option value="">Select Role*</option>
                            {roles.filter(role => role.id !== 'admin').map(role => <option key={role.id} value={role.id}>{role.name}</option>)}
                        </select>
                        <input
                            type="text" name="companyName" placeholder="Company Name" value={newUserData.companyName}
                            onChange={handleInputChange}
                            className="p-3 bg-gray-700 text-white border border-gray-600 rounded-md focus:ring-2 focus:ring-yellow-500 focus:border-yellow-500"
                        />
                        <div className="flex items-center md:col-span-2 lg:col-span-1"> {/* Adjusted span for layout */}
                            <input
                                type="checkbox" name="isActive" id="isActive" checked={newUserData.isActive}
                                onChange={handleInputChange}
                                className="h-5 w-5 text-yellow-500 bg-gray-600 border-gray-500 rounded focus:ring-yellow-400"
                            />
                            <label htmlFor="isActive" className="ml-2 text-sm text-gray-300">Active User</label>
                        </div>
                    </div>
                    <button type="submit"
                        disabled={loading}
                        className="flex items-center gap-2 bg-green-600 hover:bg-green-700 text-white px-5 py-3 rounded-md font-semibold transition-colors duration-200 disabled:opacity-50">
                        <FaPlus /> Add User
                    </button>
                </form>
            )}

            <div className="mb-4 p-4 bg-gray-800 rounded-lg border border-gray-700 flex flex-col md:flex-row justify-between items-center gap-4">
                <div className="flex flex-col md:flex-row gap-4 w-full md:w-2/3">
                    <div className="flex-1 min-w-[150px]">
                        <label className="block text-sm font-medium text-gray-400 mb-1">Filter By Field</label>
                        <select
                            value={filterType}
                            onChange={(e) => setFilterType(e.target.value)}
                            className="w-full p-2.5 bg-gray-700 text-white border border-gray-600 rounded-md focus:ring-2 focus:ring-yellow-500 focus:border-yellow-500"
                        >
                            <option value="">All Fields</option>
                            <option value="uid">User ID</option>
                            <option value="displayName">Name</option>
                            <option value="email">Email</option>
                            <option value="companyName">Company</option>
                        </select>
                    </div>
                    <div className="flex-1 min-w-[200px]">
                        <label className="block text-sm font-medium text-gray-400 mb-1">Search Users</label>
                        <input
                            type="text"
                            value={filterText}
                            onChange={(e) => setFilterText(e.target.value)}
                            placeholder={`Search ${filterType ? filterType.replace(/([A-Z])/g, ' $1').toLowerCase() : 'all fields'}...`}
                            className="w-full p-2.5 bg-gray-700 text-white border border-gray-600 rounded-md focus:ring-2 focus:ring-yellow-500 focus:border-yellow-500"
                        />
                    </div>
                </div>
                {totalPages > 1 && (
                    <div className="flex items-center space-x-1 mt-4 md:mt-0">
                        <button onClick={() => setCurrentPage(1)} disabled={currentPage === 1} className="p-2 text-xs bg-gray-700 hover:bg-gray-600 rounded disabled:opacity-50 text-white" aria-label="First page">
                            <MdFirstPage size={18} />
                        </button>
                        <button onClick={() => setCurrentPage(prev => prev - 1)} disabled={currentPage === 1} className="p-2 text-xs bg-gray-700 hover:bg-gray-600 rounded disabled:opacity-50 text-white" aria-label="Previous page">
                            <MdSkipPrevious size={18} />
                        </button>
                        <span className="text-xs text-gray-400 px-2">Page {currentPage} of {totalPages}</span>
                        <button onClick={() => setCurrentPage(prev => prev + 1)} disabled={currentPage === totalPages} className="p-2 text-xs bg-gray-700 hover:bg-gray-600 rounded disabled:opacity-50 text-white" aria-label="Next page">
                            <MdSkipNext size={18} />
                        </button>
                        <button onClick={() => setCurrentPage(totalPages)} disabled={currentPage === totalPages} className="p-2 text-xs bg-gray-700 hover:bg-gray-600 rounded disabled:opacity-50 text-white" aria-label="Last page">
                            <MdLastPage size={18} />
                        </button>
                    </div>
                )}
            </div>


            <div className="overflow-x-auto bg-gray-800 rounded-lg shadow-xl border border-gray-700">
                <table className="min-w-full divide-y divide-gray-700">
                    <thead className="bg-gray-700">
                        <tr>
                            {columns.map(col => (
                                <th key={col.key}
                                    onClick={() => col.sortable && requestSort(col.key)}
                                    className="py-3 px-4 text-left text-xs font-medium text-yellow-400 uppercase tracking-wider cursor-pointer">
                                    {col.label}
                                    {col.sortable && getSortIndicator(col.key)}
                                </th>
                            ))}
                        </tr>
                    </thead>
                    <tbody className="bg-gray-800 divide-y divide-gray-700">
                        {paginatedData.length === 0 ? (
                            <tr>
                                <td colSpan={columns.length} className="text-center py-4 text-gray-400">No users found.</td>
                            </tr>
                        ) : (
                            paginatedData.map((user) => (
                                <tr key={user.id} className="hover:bg-gray-700/50 transition-colors duration-150">
                                   {columns.map(col => (
                                        <td key={col.key} className="py-3 px-4 whitespace-nowrap text-sm">
                                            {col.render ? col.render(user[col.key], user) : (user[col.key] || 'N/A')}
                                        </td>
                                    ))}
                                </tr>
                            ))
                        )}
                    </tbody>
                </table>
            </div>
            
            <DeleteConfirmModal
                show={showDeleteConfirm}
                onClose={() => setShowDeleteConfirm(false)}
                onConfirm={confirmDeleteUser}
                title="Confirm User Deletion"
                message={`Are you sure you want to delete the user "${userToDelete?.displayName || userToDelete?.email}"? This action cannot be undone.`}
            />
        </div>
    );
};

export default UserManagement;